apiVersion: v1
appVersion: "1.0"
description: IE-MES制造执行系统是采用Java平台开发的开源企业生产管理软件，其包括系统管理、车间基础数据建模、计划管理、物料控制、生产执行、质量管理、库存管理、看板管理、数据分析等主体功能模块。广泛应用于汽车、高科技电子、医疗仪器、SMT等离散行业。通过精确物料追溯以及对人员、时间、操作信息的准确记录，为物料管理、生产控制提供准确的参考数据，以便进行预估和统计分析
icon: https://raw.githubusercontent.com/sanbaideng/rancherapp/master/charts/icons/MES制造执行系统.jpg
keywords:
- web
name: mes
version: 0.1.0
