apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "gitlab.fullname" . }}
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: {{ template "gitlab.fullname" . }}
    spec: 
      hostname: gitlab-test
      containers: 
      - name: {{ template "gitlab.fullname" . }}
        image: gitlab/gitlab-ce
        ports: 
          - containerPort: 80
          - containerPort: 22
          - containerPort: 443
        volumeMounts: 
        - mountPath: "/etc/gitlab"
          name: {{ .Values.persistence.config }}
        - mountPath: "/var/log/gitlab"
          name: {{ .Values.persistence.log }}
        - mountPath: "/var/opt/gitlab"
          name: {{ .Values.persistence.data }}
      volumes: 
        - name: {{ .Values.persistence.config }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config }}
        - name: {{ .Values.persistence.log }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.log }}
        - name: {{ .Values.persistence.data }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data }}
