replicaCount: 1

image:
  repository: reg.cecii.cn/pub/changshayun
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  nodePort: 30041
  targetPort: 8080
  port: 8081

ingress:
  enabled: true
  annotations: {}
  path: /
  host: chart-example.local
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}
