
image:
  registry: docker.io
  repository: bitnami/phpbb
  tag: 3.2.7-debian-9-r31
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

phpbbUser: user


phpbbEmail: user@example.com

## Set to `yes` to allow the container to be started with blank passwords
## ref: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables
allowEmptyPassword: "yes"

externalDatabase:
  ## Database host
  host:

  ## Database host
  port: 3306

  ## Database user
  user: bn_phpbb

  ## Database password
  password:

  ## Database name
  database: bitnami_phpbb

mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false

  db:
    name: bitnami_phpbb
    user: bn_phpbb
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi

ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  certManager: false
  annotations:
  host: ${host}
  path: /

    ## Set this to true in order to enable TLS on the ingress record
    tls: false
    tlsSecret: phpbb.local-tls

  secrets:
service:
  type: LoadBalancer
  # HTTP Port
  port: 80
  # HTTPS Port
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster


persistence:
  enabled: false
  phpbb:
    accessMode: ReadWriteOnce
    size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

podAnnotations: {}

metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}
