image:
  repository: reg.cecii.cn/bachvio/bachvio
  tag: v1.0.0
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  host: ${host}
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
