{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" . }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.size }}Gi
  cephfs:
    path: {{ .Values.persistence.path }}
{{- toYaml .Values.persistence.ceph | nindent 4 -}}
{{- end -}}