image:
  registry: docker.io
  repository: bitnami/opencart
  tag: 3.0.3-2-debian-9-r149
  pullPolicy: IfNotPresent
opencartHost: ${host}
opencartUsername: user
opencartEmail: user@example.com
allowEmptyPassword: "yes"
externalDatabase:
  host:
  port: 3306
  user: bn_opencart
  password:
  database: bitnami_opencart
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_opencart
    user: bn_opencart
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: true
  certManager: false
  annotations:
  hosts:
  - name: opencart.local
    path: /
    tls: false
    tlsSecret: opencart.local-tls
  secrets:
persistence:
  enabled: false
  opencart:
    accessMode: ReadWriteOnce
    size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 300m
podAnnotations: {}
affinity: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r73
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"