image:
  registry: docker.io
  repository: bitnami/suitecrm
  tag: 7.11.8-debian-9-r44
  pullPolicy: IfNotPresent
suitecrmHost: ${host}
suitecrmValidateUserIP: "no"
suitecrmUsername: user
suitecrmPassword: user
suitecrmEmail: user@example.com
suitecrmLastName: Name
allowEmptyPassword: "yes"
externalDatabase:
  host:
  port: 3306
  user: bn_suitecrm
  password:
  database: bitnami_suitecrm
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_suitecrm
    user: bn_suitecrm
  rootUser:
    password: "123456"
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
resources: {}
ingress:
  enabled: true
  certManager: false
  annotations:
  hosts:
  - name: suitecrm.local
    path: /
    tls: false
    tlsSecret: suitecrm.local-tls
  secrets:
podAnnotations: {}
affinity: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r79
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"