apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: measly-llama-scilab
  labels:
    app: scilab
    chart: scilab-0.1.0
    release: measly-llama
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scilab
      release: measly-llama
  template:
    metadata:
      labels:
        app: scilab
        release: measly-llama
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: scilab
          image: "sanbaideng/scilab:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

