apiVersion: v1
kind: Service
metadata:
  name: measly-llama-starccm
  labels:
    app: starccm
    chart: starccm-0.1.0
    release: measly-llama
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30011
      name: http
  selector:
    app: starccm
    release: measly-llama
