image:
  registry: docker.io
  repository: bitnami/prestashop
  tag: 1.7.6-1-debian-9-r41
  pullPolicy: IfNotPresent
prestashopHost: ${host}
prestashopUsername: user@example.com
prestashopEmail: user@example.com
prestashopFirstName: Bitnami
prestashopLastName: User
prestashopCookieCheckIP: "no"
prestashopCountry: "us"
prestashopLanguage: "en"
allowEmptyPassword: "yes"
externalDatabase:
  host:
  port: 3306
  user: bn_jasperreports
  password:
  database: bitnami_prestashop
mariadb:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mariadb
    tag: 10.1.41-debian-9-r78
  replication:
    enabled: false
  db:
    name: bitnami_prestashop
    user: bn_prestashop
  rootUser:
    password: "123456"
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Local
ingress:
  enabled: true
  certManager: false
  annotations:
  hosts:
  - name: ${host}
    path: /
    tls: false
    tlsSecret: prestashop.local-tls
  secrets:
sessionAffinity: "None"
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 300m
livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
podAnnotations: {}
affinity: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r79
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"