apiVersion: v1
kind: Service
metadata:
  name: {{ template "bashoffice.fullname" . }}
  labels:
    app: {{ template "bashoffice.name" . }}
    chart: {{ template "bashoffice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: basho
    - port: {{ .Values.service.mysqlport }}
      targetPort: 3306
      protocol: TCP
      name: bashb
  selector:
    app: {{ template "bashoffice.name" . }}
    release: {{ .Release.Name }}
