image:
  repository: reg.cecii.cn/pub/lijian
  tag: v4.0.0
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: bachvio-test.os.cecii.cn
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

volumes: []

ceph: {}
