apiVersion: v1
description: Inbucket is an email testing application
name: inbucket
appVersion: 2.0.0
version: 3.1.0
icon: https://raw.githubusercontent.com/sanbaideng/rancherapp2/master/charts/icons/gear.png
keywords:
  - 其他
home: https://www.inbucket.org/
sources:
  - https://github.com/jhillyerd/inbucket
maintainers:
  - name: cpanato
    email: ctadeu@gmail.com
  - name: jhillyerd
    email: github@hillyerd.com
