image:
  repository: reg.cecii.cn/pub/wulian
  tag: V2
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  host: ${host}
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
