apiVersion: v1
name: li
version: 1.0
description: li
keywords:
  - er
home: ${home}
icon: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568720138739&di=b6d49fa7f631c0d81d7821b066d1fb9c&imgtype=0&src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F01552a554b3448000001bf72882778.jpg
appVersion: 1.0

