apiVersion: v1
name: devops-app
version: 1.0
description: 应用手机覅带举行飞机奥斯覅偶飞机是付几is多付付付付
keywords:
  - 产品、云华
  - 产品服务
home: ${home}
icon: https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1735300731,83723593&fm=26&gp=0.jpg
appVersion: 1.0
tags: <h1>2 登&nbsp;录</h1><p><a href="http://cloud.cecii.cn/" rel="noopener noreferrer" target="_blank">http://cloud.cecii.cn</a></p><p><img src="http://172.16.21.60:8089/profile/upload/2020/12/25/5aa2a7b416fa511dd3d2a00511481c1d.png"></p><p><br></p><h1>3. 中电云网门户网站</h1><h2>3.1 首页</h2><p>&nbsp;&nbsp;&nbsp;&nbsp;首页介绍了平台的核心能力、区域子平台、行业子平台。通过子平台介绍下的查看详情按钮可跳转至相应平台</p><p><img src="http://172.16.21.60:8089/profile/upload/2020/12/25/ab202f7d2b15bedcdbc2c34be18f472b.png"></p>
