image:
  repository: reg.cecii.cn
  tag: 072410
  port: s
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: elfinder.os.cecii.cn
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

volumes: 
  - mountPath: s
    size: 1Gi
    cephPath: ${cephpath}/default

