image:
  repository: reg.cecii.cn
  tag: v0730
  port: 80
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: elfinder.os.cecii.cn
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
