apiVersion: v1
name: Delicious
version: 5.0
description: Delicious
keywords:
  - Delicious
home: ${home}
icon: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1573190166935&di=d469b736152747415f738d05635243fc&imgtype=0&src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F015f60581f1f89a84a0e282bbe8d15.png%403000w_1l_2o_100sh.png
appVersion: 5.0

