apiVersion: v1
kind: Service
metadata:
  name: existing-panther-gthumb
  labels:
    app: gthumb
    chart: gthumb-0.1.0
    release: existing-panther
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30007
      name: http
  selector:
    app: gthumb
    release: existing-panther
