apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" . }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          {{- if .Values.image.volumes }}
          volumeMounts: 
            {{- range $index, $volume := .Values.image.volumes }}
            - name: v-{{ $index }}
              mountPath: {{ $volume.path }}
            {{- end }}             
          {{- end }}
          {{- if .Values.image.envs }}
          env:
            {{- range $index, $env := .Values.image.envs }}
            - name: "{{ $env.name }}"
              value: "{{ $env.value }}"
            {{- end }}
          {{- end }}
      {{- if .Values.image.volumes }}
      volumes: 
        {{- range $index, $volume := .Values.image.volumes }}
        - name: v-{{ $index }}
          persistentVolumeClaim:
            claimName: {{ include "mychart.fullname" $ }}-pvc-{{ $index }}
        {{- end }}
      {{- end -}}
