image:
  registry: docker.io
  repository: bitnami/phabricator
  tag: 2019.43.0-debian-9-r1
  pullPolicy: IfNotPresent
phabricatorHost: ${host}
phabricatorUsername: user
phabricatorEmail: user@example.com
phabricatorFirstName: First Name
phabricatorLastName: Last Name
mariadb:
  enabled: true
  replication:
    enabled: false
  rootUser:
    password: "123456"
  master:
    extraFlags: "--local-infile=0"
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
ingress:
  enabled: true
  certManager: false
  annotations:
  hosts:
  - name: phabricator.local
    path: /
    tls: false
    tlsSecret: phabricator.local-tls
  secrets:
resources:
  requests:
    memory: 512Mi
    cpu: 300m
podAnnotations: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r96
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"