apiVersion: v1
kind: Service
metadata:
  name: mothy-wolf-evolution
  labels:
    app: evolution
    chart: evolution-0.1.0
    release: mothy-wolf
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30004
      name: http
  selector:
    app: evolution
    release: mothy-wolf
