image:
  repository: reg.cecii.cn/pub/report-echart
  tag: latest
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  host: ${host}
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

volumes: []
