apiVersion: v1
name: KAIKAI
version: V1.0.0
description: 为用户提供云主机、云存储、云备份、桌面云、专享云、混合云、CDN、大数据等全线产品，同时为政府、医疗、教育、金融等行业打造定制化云解决方案，是政府企业客户的首选云服务商
keywords:
  - 研发设计
home: ${home}
icon: https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E5%B0%8F%E9%BB%84%E4%BA%BA%E5%9B%BE%E7%89%87&hs=2&pn=10&spn=0&di=152240&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&ie=utf-8&oe=utf-8&cl=2&lm=-1&cs=2222437586%2C2844576075&os=2331408300%2C1288725396&simid=3317315209%2C355099599&adpicid=0&lpn=0&ln=30&fr=ala&fm=&sme=&cg=&bdtype=0&oriquery=%E5%B0%8F%E9%BB%84%E4%BA%BA%E5%9B%BE%E7%89%87&objurl=http%3A%2F%2Fimg5.duitang.com%2Fuploads%2Fblog%2F201312%2F25%2F20131225165833_YJGrM.thumb.700_0.jpeg&fromurl=ippr_z2C%24qAzdH3FAzdH3Fooo_z%26e3B17tpwg2_z%26e3Bv54AzdH3Frj5rsjAzdH3F4ks52AzdH3F888m8mn0cAzdH3F1jpwtsAzdH3F&gsm=0&islist=&querylist=
appVersion: V1.0.0

