apiVersion: v1
name: 棒槌
version: 1.0
description: 棒槌
keywords:
  - 棒槌
home: ${home}
icon: https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=1561195221,646233437&fm=26&gp=0.jpg
appVersion: 1.0

