image:
  registry: docker.io
  repository: bitnami/owncloud
  tag: 10.3.0-debian-9-r0
  pullPolicy: IfNotPresent
networkPolicyApiVersion: extensions/v1beta1
ingress:
  enabled: true
  hosts:
  - name: owncloud.local
    tls: false
    certManager: false
    tlsSecret: owncloud.local-tls
    annotations:
  secrets:
owncloudHost: ${host}
owncloudUsername: user
owncloudEmail: user@example.com
allowEmptyPassword: "yes"
externalDatabase:
  host:
  port: 3306
  user: bn_owncloud
  password:
  database: bitnami_owncloud
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_owncloud
    user: bn_owncloud
  rootUser:
    password: "123456"
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
persistence:
  enabled: false
  owncloud:
    accessMode: ReadWriteOnce
    size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 300m
podAnnotations: {}
affinity: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r95
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"