# Default values for luigi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: axiom/docker-luigi
  tag: 2.7.2-alpine
  pullPolicy: IfNotPresent

service:
  name: luigi
  type: LoadBalancer
  externalPort: 80

  # Luigi config: these values should mattch the luigi documentation
  # https://luigi.readthedocs.io/en/stable/configuration.html
  config: |
    [core]
    logging_conf_file=/etc/luigi/logging.cfg

    [scheduler]
    record_task_history=true
    state-path=/luigi/state/luigi-state.pickle

    [task_history]
    db_connection=mysql://luigi-mysql/luigidb

# creates a persistent volume claim for
# luigi state pickel
persistence:
  enabled: false
  size: 1G
  accessMode: ReadWriteOnce

# Ingress for ui access for use with authentication like oauth-proxy
# depending on the authentication you use. You may only need one ingress.
ingressUI:
  enabled: true
  path: /
  # Used to create an Ingress record.
  host: ${host}
ingressAPI:
  enabled: false
  path: /

resources: {}

mysql:
  mysqlDatabase: luigidb
  mysqlAllowEmptyPassword: true
  persistence:
    enabled: false
