apiVersion: v1
kind: Service
metadata:
  name: { { template "smtdiagnose.fullname" . } }
  labels:
    app: { { template "smtdiagnose.name" . } }
    chart: { { template "smtdiagnose.chart" . } }
    release: { { .Release.Name } }
    heritage: { { .Release.Service } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: TCP
      name: http
  selector:
    app: { { template "smtdiagnose.name" . } }
    release: { { .Release.Name } }
