image:
  registry: docker.io
  repository: bitnami/drupal
  tag: 8.7.3-debian-9-r6

  pullPolicy: IfNotPresent

drupalProfile: standard

drupalUsername: user
drupalEmail: user@example.com
allowEmptyPassword: "yes"

externalDatabase:

mariadb:
  enabled: true
  replication:
    enabled: false

  db:
    name: bitnami_drupal
    user: bn_drupal

  master:
    persistence:
      enabled: false

      accessMode: ReadWriteOnce
      size: 8Gi

service:
  type: LoadBalancer
  # HTTP Port
  port: 80
  # HTTPS Port
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""

  externalTrafficPolicy: Cluster

ingress:
  enabled: true
  host: ${host}
    tls: false
    certManager: false
    tlsSecret: drupal.local-tls

    annotations:

persistence:
  enabled: false
  drupal:

    accessMode: ReadWriteOnce
    size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

volumeMounts:
  drupal:
    mountPath: /bitnami/drupal

## Pass extra environment variables to the Drupal container.
##
livenessProbe:
  httpGet:
    path: /user/login
    port: http
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /user/login
    port: http
  initialDelaySeconds: 30

podAnnotations: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
