apiVersion: v1
name: test2020122901
version: 3.0
description: 测试3.0
keywords:
  - 测试
  - 研发设计
home: ${home}
icon: https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1735300731,83723593&fm=26&gp=0.jpg
appVersion: 3.0

