apiVersion: v1
name: test2020122901
version: 1.0
description: 测试111
keywords:
  - 1111
  - 研发设计
home: ${home}
icon: https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1735300731,83723593&fm=26&gp=0.jpg
appVersion: 1.0

