global: 
  storageAddr: ""
  storagePath: ""
  namespace: "default"
  releaseName: ""
  cephUser: "admin"
  cephSecret: "ceph-secret-client-admin"
appmain:
  pv: true
  pvc: true
  capacity: 1Gi
  ingress: "gitlab.cecii.cn"
  path: ""