image:
  repository: reg.cecii.cn/javaweb2/javaweb2
  tag: v1.0.0
  dbUrl: "jdbc:mysql://javaweb2-mysql:3306/javaweb"
  dbUsername: root
  dbPassword: "123456"
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: javaweb2.os.cecii.cn
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

volumes: []

ceph: {}

mysql: 
  image:
    repository: mysql
    tag: 5.7.26
    port: 3306
    rootPass: "123456"
    pullPolicy: IfNotPresent 
  conf: 
    enabled: true
    image: reg.cecii.cn/mysql-data/cnf
    imageTag: v1.0.0
    filePath: /cnf
    pullPolicy: Always
  sql: 
    enabled: true
    image: reg.cecii.cn/mysql-data/sql
    imageTag: v1.0.0
    filePath: /sql
    pullPolicy: Always
  persistence: 
    enabled: true
    size: 3
    ceph: 
      monitors:
        - 192.168.1.20:6789
        - 192.168.1.22:6789
        - 192.168.1.23:6789 
      user: admin
      secretRef: 
        name: ceph-secret-client-admin
    path: /javaweb2/mysql
  service:
    name: javaweb2-mysql
    type: ClusterIP
  nameOverride: ""
  fullnameOverride: ""
  replicaCount: 1