{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "osclass.fullname" . }}
  labels:
    app: "{{ template "osclass.fullname" . }}"
    chart: "{{ template "osclass.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.osclassHost }}
    http:
      paths:
      - path: {{ "/"  }}
        backend:
          serviceName: {{ template "osclass.fullname" $ }}
          servicePort: http
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
  {{- if .tlsHosts }}
  {{- range $host := .tlsHosts }}
    - {{ $host }}
  {{- end }}
  {{- else }}
    - {{ .name }}
  {{- end }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  {{- end }}
{{- end }}
