apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: looming-greyhound-rhythmbox
  labels:
    app: rhythmbox
    chart: rhythmbox-0.1.0
    release: looming-greyhound
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhythmbox
      release: looming-greyhound
  template:
    metadata:
      labels:
        app: rhythmbox
        release: looming-greyhound
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: rhythmbox
          image: "sanbaideng/rhythmbox:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

