apiVersion: v1
kind: Service
metadata:
  name: looming-greyhound-rhythmbox
  labels:
    app: rhythmbox
    chart: rhythmbox-0.1.0
    release: looming-greyhound
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
      name: http
  selector:
    app: rhythmbox
    release: looming-greyhound
