apiVersion: v1
kind: Service
metadata:
  name: mangy-toucan-thunderbird
  labels:
    app: thunderbird
    chart: thunderbird-0.1.0
    release: mangy-toucan
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30012
      name: http
  selector:
    app: thunderbird
    release: mangy-toucan

