## Image Settings
##
image:
  repository: "docker.io/chronograf"
  tag: "1.7.7-alpine"
  pullPolicy: "Always"

service:
  replicas: 1
  type: ClusterIP

## Persist data to a persistent volume
##
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2

## Configure the ingress object to hook into existing infastructure
## ref : http://kubernetes.io/docs/user-guide/ingress/
## OPTIONALLY you can set .Values.ingress.secretName to set which secret to use
##
ingress:
  enabled: true
  tls: false
  hostname: ${host}
  annotations:

oauth:
  # Need to set to true to use any of the oauth options
  enabled: false
  # Used for JWT to support running multiple copies of Chronograf
  token_secret: CHANGE_ME
  github:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # This is a comma separated list of GH organizations (OPTIONAL)
    gh_orgs: ""
  google:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # eg. http://chronograf.foobar.com
    public_url: ""
    # This is a comma separated list of Google Apps domains (OPTIONAL)
    domains: ""
  heroku:
    enabled: false
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    # This is a comma separated list of Heroku organizations (OPTIONAL)
    he_orgs: ""

## Extra environment variables that will be passed onto deployment pods
env: {}

envFromSecret: ""
