apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mangy-toucan-thunderbird
  labels:
    app: thunderbird
    chart: thunderbird-0.1.0
    release: mangy-toucan
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunderbird
      release: mangy-toucan
  template:
    metadata:
      labels:
        app: thunderbird
        release: mangy-toucan
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: thunderbird
          image: "sanbaideng/thunderbird:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

