
image:
  registry: docker.io
  repository: bitnami/orangehrm
  tag: 4.3.1-0-debian-9-r20
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

orangehrmUsername: admin
allowEmptyPassword: "yes"

##
## External database configuration
##
externalDatabase:
  ## Database host
  host:

  ## Database host
  port: 3306

  ## Database user
  user: bn_orangehrm

  ## Database password
  password:

  ## Database name
  database: bitnami_orangehrm

mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_orangehrm
    user: bn_orangehrm

  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi

service:
  type: LoadBalancer
  # HTTP Port
  port: 80
  # HTTPS Port
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""

  externalTrafficPolicy: Cluster


persistence:
  enabled: false
  orangehrm:
    accessMode: ReadWriteOnce
    size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

podAnnotations: {}

ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  annotations:
  host: ${host}
  path: /

    ## Set this to true in order to enable TLS on the ingress record
    tls: false

    tlsSecret: orangehrm.local-tls

  secrets:
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
