volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: stretch
    pullPolicy: Always
  resources: {}
service:
  type: LoadBalancer
  port: 80
  nodePorts:
    http: ""
  externalTrafficPolicy: Cluster
server:
  image:
    registry: docker.io
    repository: bitnami/parse
    tag: 3.9.0-debian-9-r8
    pullPolicy: IfNotPresent
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  port: 1337
  mountPath: /parse
  appId: myappID
  enableCloudCode: false
  resources: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  affinity: {}
  nodeSelector: {}
  tolerations: {}
dashboard:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/parse-dashboard
    tag: 2.0.3-debian-9-r1
    pullPolicy: IfNotPresent
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  username: user
  appName: MyDashboard
  resources: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 240
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  affinity: {}
  nodeSelector: {}
  tolerations: {}
ingress:
  enabled: true
  certManager: false
  annotations:
  dashboard:
    hosts:
      - name: ${host}
        path: /
        tls: false
        tlsSecret: parse.local-tls
  server:
    hosts:
      - name: parse-server.local
        path: /
        tls: false
        tlsSecret: parse.local-tls
  secrets:
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
mongodb:
  usePassword: true
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi