{{ if .Values.volumes }}
{{- range $index, $volume := .Values.volumes -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
    helm.sh/chart: {{ include "mychart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $volume.size }}Gi
{{- toYaml $.Values.ceph | nindent 4 }}
---
{{ end }}
{{ end }}
