{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "redmine.fullname" $ }}
  labels:
    app: {{ template "redmine.fullname" $ }}
    chart: {{ template "redmine.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    {{- if .certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          serviceName: {{ template "redmine.fullname" $ }}
          servicePort: 80
{{- if .tls }}
  tls:
    - secretName: {{ .tlsSecret }}
      hosts:
        - {{ .name }}
{{- end }}
---
{{- end }}
