image:
  registry: docker.io
  repository: bitnami/osclass
  tag: 3.7.4-debian-9-r393
  pullPolicy: IfNotPresent
osclassHost: ${host}
osclassUsername: user
osclassEmail: user@example.com
osclassWebTitle: 'Sample Web Page'
osclassPingEngines: 1
osclassSaveStats: 1
allowEmptyPassword: "yes"
externalDatabase:
  host:
  port: 3306
  user: bn_osclass
  password:
  database: bitnami_osclass
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_osclass
    user: bn_osclass
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: true
  certManager: false
  annotations:
  hosts:
  - name: osclass.local.com
    path: /
    tls: false
    tlsSecret: osclass.local-tls
  secrets:
persistence:
  enabled: false
  osclass:
    accessMode: ReadWriteOnce
    size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 300m
podAnnotations: {}
affinity: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r95
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"