image:
  registry: docker.io
  repository: bitnami/redmine
  tag: 4.0.4-debian-9-r0

  pullPolicy: IfNotPresent

redmineUsername: user


redmineEmail: user@example.com


redmineLanguage: en


databaseType:
  mariadb: true
  postgresql: false


mariadb:
  enabled: true
  replication:
    enabled: false

  db:
    name: bitnami_redmine
    user: bn_redmine

  master:
    persistence:
      enabled: false

      accessMode: ReadWriteOnce
      size: 8Gi

postgresql:
  enabled: false
  persistence:
    enabled: false

    accessMode: ReadWriteOnce
    size: 8Gi

externalDatabase:
  host: localhost
  user: root
  password: ""
  port: 3306


service:
  type: LoadBalancer
  # HTTP Port
  port: 80
  ## loadBalancerIP:
  ## Control hosts connecting to "LoadBalancer" only
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ##
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  nodePorts:
    http: ""
  externalTrafficPolicy: Cluster
ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  host: ${host}
    tls: false
    certManager: false
    tlsSecret: redmine.local-tls

    annotations:

nodeSelector: {}

tolerations: {}

affinity: {}

podAnnotations: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi

podDisruptionBudget:
  enabled: false
replicas: 1

## Redmine pods resource requests and limits
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container
resources: {}
  # requests:
  #   cpu: "1"
  #   memory: "1G"
  # limits:
  #   cpu: "2"
  #   memory: "1G"
