# Default values for node-red.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

image:
  repository: nodered/node-red-docker
  tag: 0.20.5-slim-v8
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

flows: "flows.json"
# nodeOptions: ""
timezone: "UTC"

service:
  type: ClusterIP
  port: 1880
  annotations: {}
  labels: {}

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  host: ${host}
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: false

  accessMode: ReadWriteOnce
  size: 5Gi
  ## When mounting the data volume you may specify a subPath
  # subPath: /configs/node-red

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}
