apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "weberp.fullname" . }}
  labels:
    app: {{ template "weberp.name" . }}
    chart: {{ template "weberp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "weberp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "weberp.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}
