apiVersion: v1
kind: Service
metadata:
  name: quarrelsome-lemur-freecad
  labels:
    app: freecad
    chart: freecad-0.1.0
    release: quarrelsome-lemur
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30005
      name: http
  selector:
    app: freecad
    release: quarrelsome-lemur
