apiVersion: v1
appVersion: "1.0"
description: Inkscape是一款外国开发的开源矢量图形编辑软件，与Illustrator、Freehand、CorelDraw、Xara X 等其他软件相似
icon: https://markdowna.oss-cn-shenzhen.aliyuncs.com/icon/inkscape.jpg
keywords:
  - gui
  - 协同设计
  - 研发设计
name: inkscape
version: 0.1.0
