apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: masked-donkey-inkscape
  labels:
    app: inkscape
    chart: inkscape-0.1.0
    release: masked-donkey
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inkscape
      release: masked-donkey
  template:
    metadata:
      labels:
        app: inkscape
        release: masked-donkey
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: inkscape
          image: "sanbaideng/inkscape:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

