apiVersion: v1
kind: Service
metadata:
  name: masked-donkey-inkscape
  labels:
    app: inkscape
    chart: inkscape-0.1.0
    release: masked-donkey
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30008
      name: http
  selector:
    app: inkscape
    release: masked-donkey
