image:
  registry: docker.io
  repository: bitnami/joomla
  tag: 3.9.12-debian-9-r25
  pullPolicy: IfNotPresent
joomlaUsername: user
joomlaEmail: user@example.com
allowEmptyPassword: "yes"
externalDatabase:
  host: localhost
  port: 3306
  user: bn_joomla
  password: ""
  database: bitnami_joomla
mariadb:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mariadb
    tag: 10.1.41-debian-9-r92
  replication:
    enabled: false
  db:
    name: bitnami_joomla
    user: bn_joomla
  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: true
  hosts:
  - name: ${host}
    tls: false
    certManager: false
    tlsSecret: joomla.local-tls
    annotations:
  secrets:
persistence:
  enabled: false
  joomla:
    accessMode: ReadWriteOnce
    size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 300m
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-9-r92
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"