apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    name: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.size | quote }}
  selector:
    matchLabels:
      name: {{ template "mysql.fullname" . }}
