image:
  name: "reg.cecii.cn/elfinder06/sdfsfsf"
  tag: "v1"
  port: 1213

  volumes: []

  envs: []

ceph:
  monitors:
    - 172.16.20.7:6789
    - 172.16.20.239:6789
    - 172.16.20.77:6789
  user: admin
  secret: $ceph.secret

ingress:
  enabled: true
  host: ${host}

