apiVersion: v1
name: test0927
version: 1.0
description: mvn clean package
keywords:
  - test0927
home: ${home}
icon: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1569563694748&di=a9c80aabf5cb26a44dce1992f067469a&imgtype=0&src=http%3A%2F%2Fpic1.16pic.com%2F00%2F51%2F76%2F16pic_5176356_b.jpg
appVersion: 1.0

