apiVersion: v1
kind: Service
metadata:
  name: {{ template "netbeans.fullname" . }}
  labels:
    app: {{ template "netbeans.name" . }}
    chart: {{ template "netbeans.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    app: {{ template "netbeans.name" . }}
    release: {{ .Release.Name }}
