apiVersion: v1
appVersion: "1.0"
description: AgileBPM是一款开源的办公系统，里面包含了系统模块、流程模块、表单模块等，能够快速灵活构建不同的流程
icon: https://markdowna.oss-cn-shenzhen.aliyuncs.com/icon/bpm.jpg
keywords:
  - 企业管理
  - 研发设计
name: bpm
version: 0.1.0
