apiVersion: v1
name: mestest
version: 1.0
description: we
keywords:
  - we
home: ${home}
icon: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1569304053216&di=65078f75a435762e4875a2068ccb0e6b&imgtype=0&src=http%3A%2F%2Fpic.51yuansu.com%2Fpic3%2Fcover%2F01%2F18%2F96%2F59051eca0ce28_610.jpg
appVersion: 1.0

