apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: irreverant-cat-netbeans
  labels:
    app: netbeans
    chart: netbeans-0.1.0
    release: irreverant-cat
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbeans
      release: irreverant-cat
  template:
    metadata:
      labels:
        app: netbeans
        release: irreverant-cat
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: netbeans
          image: "sanbaideng/netbeans:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

