apiVersion: v1
kind: Service
metadata:
  name: irreverant-cat-netbeans
  labels:
    app: netbeans
    chart: netbeans-0.1.0
    release: irreverant-cat
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30009
      name: http
  selector:
    app: netbeans
    release: irreverant-cat

