image:
  repository: reg.cecii.cn/javaweb/javaweb
  tag: v1.0.0
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: javaweb.os.cecii.cn
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

volumes: []

ceph: {}
