apiVersion: v1
description: A lightweight private npm proxy registry (sinopia fork)
name: verdaccio
version: 0.7.1
appVersion: 3.11.6
icon: https://markdowna.oss-cn-shenzhen.aliyuncs.com/icon/gear.png
home: http://www.verdaccio.org
sources:
- http://www.verdaccio.org
- https://github.com/verdaccio/verdaccio
keywords:
- 其他
- 研发设计
maintainers:
- name: etiennetremel
  email: etienne.tremel@container-solutions.com
