{{ if .Values.image.volumes }}
{{- $cephMonitors := .Values.ceph.monitors -}}
{{- $cephUser := .Values.ceph.user -}}
{{- $cephSecret := .Values.ceph.secret -}}
{{- range $index, $volume := .Values.image.volumes -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
    helm.sh/chart: {{ include "mychart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $volume.size }}Gi
  cephfs:
    monitors:
      {{- range $index, $monitor := $cephMonitors }}
      - {{ $monitor }}
      {{- end }}
    path: {{ $volume.cephPath }}
    user: {{ $cephUser }}
    secretRef:
      name: {{ $cephSecret }}
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" $ }}-pvc-{{ $index }}
  labels:
    app.kubernetes.io/name: {{ include "mychart.fullname" $ }}-pvc-{{ $index }}
    helm.sh/chart: {{ include "mychart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.size }}Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
  volumeName: {{ include "mychart.fullname" $ }}-pv-{{ $index }}
---
{{ end }}
{{ end }}