apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: exegetical-gibbon-bachhr
  labels:
    app: bachhr
    chart: bachhr-0.1.0
    release: exegetical-gibbon
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bachhr
      release: exegetical-gibbon
  template:
    metadata:
      labels:
        app: bachhr
        release: exegetical-gibbon
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: bachhr
          image: "sanbaideng/bachhr:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

