replicaCount: 1
deploymentStrategy: RollingUpdate
image:
  repository: hackmdio/hackmd
  tag: 1.3.0-alpine
  pullPolicy: IfNotPresent
service:
  name: hackmd
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - ${host}
  tls: []
resources: {}
persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  annotations: {}
  existingClaim: ""
  size: 2Gi
podAnnotations: {}
extraVars: []
nodeSelector: {}
tolerations: []
affinity: {}
postgresql:
  install: true
  imageTag: "9.6.2"
  postgresUser: "hackmd"
  postgresDatabase: "hackmd"