{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "moodle.fullname" $ }}
  labels:
    app: {{ template "moodle.fullname" $ }}
    chart: {{ template "moodle.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    {{- if .certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.appmain.ingress }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "moodle.fullname" $ }}
            servicePort: 80
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
{{- end }}
---
{{- end }}




