apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gaudy-ibex-gimp
  labels:
    app: gimp
    chart: gimp-0.1.0
    release: gaudy-ibex
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gimp
      release: gaudy-ibex
  template:
    metadata:
      labels:
        app: gimp
        release: gaudy-ibex
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: gimp
          image: "sanbaideng/gimp:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

