apiVersion: v1
kind: Service
metadata:
  name: gaudy-ibex-gimp
  labels:
    app: gimp
    chart: gimp-0.1.0
    release: gaudy-ibex
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30006
      name: http
  selector:
    app: gimp
    release: gaudy-ibex

