image:
  repository: reg.cecii.cn/pub/echart-logo
  tag: latest
  port: 80
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  host: echart-logo.os.cecii.cn
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

volumes: []
