image:
  repository: reg.cecii.cn/elfinder06/elfinder
  tag: v1.0
  port: 8080
  pullPolicy: Always
    
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: ${host}
  tls: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

