apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: famous-mule-blender
  labels:
    app: blender
    chart: blender-0.1.0
    release: famous-mule
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blender
      release: famous-mule
  template:
    metadata:
      labels:
        app: blender
        release: famous-mule
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: blender
          image: "sanbaideng/blender:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}

