apiVersion: v1
description: Prometheus Blackbox Exporter
name: prometheus-blackbox-exporter
version: 0.3.0
appVersion: 0.14.0
icon: https://markdowna.oss-cn-shenzhen.aliyuncs.com/icon/gear.png
home: https://github.com/prometheus/blackbox_exporter
sources:
  - https://github.com/prometheus/blackbox_exporter
keywords:
- 其他
- 研发设计
maintainers:
  - name: gianrubio
    email: gianrubio@gmail.com
