apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wavesolderinganalyze.fullname" . }}
  labels:
    app: {{ template "wavesolderinganalyze.name" . }}
    chart: {{ template "wavesolderinganalyze.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "wavesolderinganalyze.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "wavesolderinganalyze.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: vol
              mountPath: /sys/fs/cgroup
              readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources: {}
