apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ulterior-sabertooth-gnucash
  labels:
    app: gnucash
    chart: gnucash-0.1.0
    release: ulterior-sabertooth
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnucash
      release: ulterior-sabertooth
  template:
    metadata:
      labels:
        app: gnucash
        release: ulterior-sabertooth
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /sys/fs/cgroup
      containers:
        - name: gnucash
          image: "sanbaideng/gnucash:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: vol
            mountPath: /sys/fs/cgroup
            readOnly: true
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: myport
              containerPort: 3389
              protocol: TCP
          resources:
            {}
