apiVersion: v1
kind: Service
metadata:
  name: rude-snake-bashoffice
  labels:
    app: bashoffice
    chart: bashoffice-0.1.0
    release: rude-snake
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 80
      protocol: TCP
      nodePort: 30089
      name: bash
    - port: 8083
      targetPort: 3306
      protocol: TCP
      nodePort: 32060
      name: mysql
  selector:
    app: bashoffice
    release: rude-snake

